name:                lucid-htmx
version:             0.1.0.0
github:              "githubuser/lucid-htmx"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/lucid-htmx#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- containers
- contravariant-extras
- css-selectors
- hasql
- hasql-th
- hedis
- lucid
- profunctors
- servant
- servant-lucid
- servant-server
- text
- tuple
- vector
- warp

library:
  source-dirs: src

executables:
  lucid-htmx-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lucid-htmx
  
  lucid-htmx-ex0-exe:
    main: example0/Main.hs
    source-dirs:
    - examples
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lucid-htmx

  lucid-htmx-ex1-exe:
    main: example1/Main.hs
    source-dirs:
    - examples
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lucid-htmx

tests:
  lucid-htmx-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lucid-htmx
